const FALLBACK_DATA=[{"rank":1,"brand":"현대","model":"팰리세이드","generation":"LX2","year":2019,"retention":78,"depreciation":22,"sample":134,"category":"대형 SUV"},{"rank":2,"brand":"현대","model":"싼타페","generation":"TM","year":2018,"retention":70.2,"depreciation":29.8,"sample":627,"category":"중형 SUV"}];
const $=id=>document.getElementById(id),body=$('rankingBody'),brand=$('brandFilter'),category=$('categoryFilter');
let DATA=[...FALLBACK_DATA],VEHICLES=[],COMPARE=[],RATINGS=[],REVIEWS=[],OWNER_RANKING=[];
const CRITERIA=[['ride_comfort','승차감'],['quietness','정숙성'],['performance','주행성능'],['fuel_efficiency','연비'],['maintenance_cost','유지비'],['reliability','잔고장/신뢰성'],['design','디자인'],['convenience','편의장비'],['resale_value','중고가치'],['repurchase_intent','재구매의향']];
function cfg(){return window.CARRANKING_CONFIG||{}}
function headers(extra={}){const c=cfg();return {apikey:c.supabasePublishableKey,Authorization:`Bearer ${c.supabasePublishableKey}`,...extra}}
async function api(view,query='select=*'){const c=cfg();if(!c.useSupabase)return[];const r=await fetch(`${c.supabaseUrl}/rest/v1/${view}?${query}`,{headers:headers()});if(!r.ok)throw new Error(`${view} HTTP ${r.status}`);return r.json()}
async function rpc(fn,payload){const c=cfg();const r=await fetch(`${c.supabaseUrl}/rest/v1/rpc/${fn}`,{method:'POST',headers:headers({'Content-Type':'application/json'}),body:JSON.stringify(payload)});if(!r.ok){const t=await r.text();throw new Error(`${fn} HTTP ${r.status}: ${t}`)}return r.json()}
function pct(v){return v==null?'정보 없음':`${(Number(v)*100).toFixed(1)}%`}function won(v){return v==null?'정보 없음':`${Math.round(Number(v)/10000).toLocaleString()}만원`}function mm(v){return v==null?'정보 없음':`${Number(v).toLocaleString()} mm`}function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function vehicleLabel(v){return `${v.brand} ${v.model} ${v.generation_code||v.generation||''}`.trim()}
function visitorId(){let v=localStorage.getItem('carranking_visitor');if(!v){v=(crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`);localStorage.setItem('carranking_visitor',v)}return v}
function fillRankingFilters(){brand.innerHTML='<option value="">전체 브랜드</option>';category.innerHTML='<option value="">전체 차급</option>';[...new Set(DATA.map(x=>x.brand).filter(Boolean))].sort().forEach(v=>brand.insertAdjacentHTML('beforeend',`<option>${esc(v)}</option>`));[...new Set(DATA.map(x=>x.category).filter(Boolean))].sort().forEach(v=>category.insertAdjacentHTML('beforeend',`<option>${esc(v)}</option>`))}
function renderHero(){const x=DATA[0];if(x)$('heroCard').innerHTML=`<div class="metric-label">가치보존율 1위</div><div class="car-name">${esc(x.brand)} ${esc(x.model)} ${esc(x.generation_code||x.generation||'')}</div><div class="big">${pct(x.retention_rate??x.retention/100)}</div><div class="muted">${esc(x.model_year??x.year??'-')}년식 · 참고 데이터</div>`}
function renderRanking(){const list=DATA.filter(x=>(!brand.value||x.brand===brand.value)&&(!category.value||x.category===category.value));body.innerHTML=list.map((x,i)=>`<tr class="clickable-row" data-brand="${esc(x.brand)}" data-model="${esc(x.model)}" data-generation="${esc(x.generation_code??x.generation??'')}"><td><strong>#${x.rank??i+1}</strong></td><td><strong>${esc(x.brand)} ${esc(x.model)}</strong><span class="muted-dark small">${esc(x.generation_code??x.generation??'')}</span></td><td>${esc(x.model_year??x.year??'-')}</td><td><span class="badge">${pct(x.retention_rate??x.retention/100)}</span></td><td>${pct(x.depreciation_rate??x.depreciation/100)}</td><td>${esc(x.sample_size??x.sample??'미확보')}</td></tr>`).join('');document.querySelectorAll('.clickable-row').forEach(r=>r.onclick=()=>openDetail(r.dataset.brand,r.dataset.model,r.dataset.generation))}
function fillVehicleSelectors(){const o=[...VEHICLES].sort((a,b)=>vehicleLabel(a).localeCompare(vehicleLabel(b),'ko')),opts=o.map(v=>`<option value="${esc(v.generation_id)}">${esc(vehicleLabel(v))}</option>`).join('');['compare1','compare2','compare3'].forEach((id,i)=>$(id).innerHTML=`<option value="">차량 ${i+1} 선택${i===2?' (선택)':''}</option>`+opts);$('reviewVehicle').innerHTML='<option value="">차량/세대 선택</option>'+opts;const bs=[...new Set(o.map(v=>v.brand))].sort((a,b)=>a.localeCompare(b,'ko'));$('scoreBrand').innerHTML='<option value="">브랜드 선택</option>'+bs.map(v=>`<option>${esc(v)}</option>`).join('');updateScoreVehicles()}
function updateScoreVehicles(){const b=$('scoreBrand').value,l=VEHICLES.filter(v=>!b||v.brand===b).sort((a,b)=>vehicleLabel(a).localeCompare(vehicleLabel(b),'ko'));$('scoreVehicle').innerHTML='<option value="">모델/세대 선택</option>'+l.map(v=>`<option value="${esc(v.generation_id)}">${esc(vehicleLabel(v))}</option>`).join('')}
function detailCard(l,v,s=''){return `<div class="metric-card"><span>${esc(l)}</span><strong>${esc(v)}</strong>${s?`<small>${esc(s)}</small>`:''}</div>`}
function ownerBreakdown(r){if(!r)return'<p class="notice">아직 오너평가가 없습니다.</p>';return `<div class="owner-breakdown"><h3>오너 평가 상세</h3><div class="criteria-bars">${CRITERIA.map(([k,n])=>`<div class="criteria-row"><span>${esc(n)}</span><div class="bar"><i style="width:${Math.max(0,Math.min(100,Number(r[k]||0)*10))}%"></i></div><strong>${Number(r[k]||0).toFixed(1)}</strong></div>`).join('')}</div></div>`}
function openDetail(b,m,g){const v=VEHICLES.find(x=>x.brand===b&&x.model===m&&(!g||x.generation_code===g||x.generation===g));if(!v)return;const r=RATINGS.find(x=>String(x.generation_id)===String(v.generation_id));$('detailTitle').textContent=vehicleLabel(v);$('detailContent').innerHTML=[detailCard('차급',v.category||'정보 없음'),detailCard('생산 기간',`${v.start_year||'-'} ~ ${v.current?'현재':v.end_year||'-'}`),detailCard('신차 기준가',won(v.original_price_krw)),detailCard('중고 기준가',won(v.used_price_krw)),detailCard('가치보존율',pct(v.retention_rate)),detailCard('오너평점',r?`${Number(r.overall_score).toFixed(1)} / 10`:'평가 데이터 부족',r?`${r.rating_count}명 평가`:''),detailCard('감가율',pct(v.depreciation_rate)),detailCard('데이터 신뢰도',v.confidence||'정보 없음')].join('');const vr=REVIEWS.filter(x=>String(x.generation_id)===String(v.generation_id)).slice(0,3);$('detailOwner').innerHTML=ownerBreakdown(r)+(vr.length?`<div class="detail-review-list"><h3>최근 오너리뷰</h3>${vr.map(x=>`<article class="review-card">${x.title?`<h4>${esc(x.title)}</h4>`:''}<p>${esc(x.body)}</p><span>${esc(x.display_name||'익명 오너')} · ${new Date(x.created_at).toLocaleDateString('ko-KR')}</span></article>`).join('')}</div>`:'');$('vehicleDetail').classList.remove('hidden');$('vehicleDetail').scrollIntoView({behavior:'smooth'})}
function renderComparison(ids){const rows=ids.map(id=>COMPARE.find(v=>String(v.generation_id)===String(id))).filter(Boolean);if(rows.length<2){$('compareResult').innerHTML='<p class="notice">비교할 차량을 2대 이상 선택해 주세요.</p>';return}const metrics=[['차급',v=>v.category||'정보 없음'],['전장',v=>mm(v.length_mm)],['전폭',v=>mm(v.width_mm)],['전고',v=>mm(v.height_mm)],['휠베이스',v=>mm(v.wheelbase_mm)],['복합 효율',v=>v.combined_efficiency||'정보 없음'],['가치보존율',v=>pct(v.retention_rate)],['감가율',v=>pct(v.depreciation_rate)],['오너평점',v=>{const r=RATINGS.find(x=>String(x.generation_id)===String(v.generation_id));return r?`${Number(r.overall_score).toFixed(1)} / 10 (${r.rating_count}명)`:'평가 데이터 부족'}]];$('compareResult').innerHTML=`<div class="table-wrap"><table class="compare-table"><thead><tr><th>항목</th>${rows.map(v=>`<th>${esc(vehicleLabel(v))}</th>`).join('')}</tr></thead><tbody>${metrics.map(([n,f])=>`<tr><th>${n}</th>${rows.map(v=>`<td>${esc(f(v))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function quickCompare(pair){const f=pair.split('|').map(n=>COMPARE.find(v=>v.model===n)).filter(Boolean);if(f.length<2)return;$('compare1').value=f[0].generation_id;$('compare2').value=f[1].generation_id;renderComparison(f.map(v=>v.generation_id))}
function showScore(){const id=$('scoreVehicle').value,v=VEHICLES.find(x=>String(x.generation_id)===String(id));if(!v){$('scoreResult').innerHTML='<p class="notice">차량을 선택해 주세요.</p>';return}const r=RATINGS.find(x=>String(x.generation_id)===String(id));$('scoreResult').innerHTML=`<div class="score-summary"><strong>${esc(vehicleLabel(v))}</strong><span>가치보존율 ${pct(v.retention_rate)}</span><span>오너 종합평점 ${r?`${Number(r.overall_score).toFixed(1)} / 10 (${r.rating_count}명)`:'평가 데이터 부족'}</span>${r?`<span>신뢰성 ${Number(r.reliability).toFixed(1)} · 승차감 ${Number(r.ride_comfort).toFixed(1)} · 재구매 ${Number(r.repurchase_intent).toFixed(1)}</span>`:''}</div>`}
function buildRatingFields(){$('ratingFields').innerHTML=CRITERIA.map(([k,n])=>`<label><span>${n}</span><select name="${k}" required><option value="">점수</option>${[10,9,8,7,6,5,4,3,2,1].map(v=>`<option value="${v}">${v}점</option>`).join('')}</select></label>`).join('')}
function renderOwnerRanking(){const box=$('ownerRankingList');if(!OWNER_RANKING.length){box.innerHTML='<div class="empty"><strong>아직 오너랭킹 데이터가 없습니다.</strong><p>첫 평가가 등록되면 자동으로 순위가 생성됩니다.</p></div>';return}const rows=[...OWNER_RANKING].sort((a,b)=>Number(b.overall_score)-Number(a.overall_score)||Number(b.rating_count)-Number(a.rating_count)).slice(0,12);box.innerHTML=rows.map((r,i)=>`<article class="owner-rank-card" data-gid="${esc(r.generation_id)}"><b>#${i+1}</b><div><strong>${esc(r.brand)} ${esc(r.model)}</strong><span>${esc(r.generation_code||r.generation||'')} · ${Number(r.rating_count)}명 평가</span></div><em>${Number(r.overall_score).toFixed(1)}</em></article>`).join('');document.querySelectorAll('.owner-rank-card').forEach(el=>el.onclick=()=>{const v=VEHICLES.find(x=>String(x.generation_id)===String(el.dataset.gid));if(v)openDetail(v.brand,v.model,v.generation_code||v.generation)})}
function renderReviews(){const count=RATINGS.reduce((s,r)=>s+Number(r.rating_count||0),0);$('reviewSummary').innerHTML=`<strong>누적 오너평가 ${count.toLocaleString()}건</strong><span>등록된 평점은 10개 항목 가중평균에 자동 반영됩니다.</span>`;$('reviewFeed').innerHTML=REVIEWS.length?REVIEWS.map(r=>`<article class="review-card"><div><strong>${esc([r.brand,r.model,r.generation_code||r.generation].filter(Boolean).join(' '))}</strong><span>${esc(r.display_name||'익명 오너')} · ${new Date(r.created_at).toLocaleDateString('ko-KR')}</span></div>${r.title?`<h4>${esc(r.title)}</h4>`:''}<p>${esc(r.body)}</p></article>`).join(''):'<div class="empty"><strong>첫 오너 리뷰를 남겨주세요.</strong><p>아직 공개된 리뷰가 없습니다.</p></div>'}
async function refreshOwnerData(){try{[RATINGS,REVIEWS,OWNER_RANKING]=await Promise.all([api('web_rating_summary','select=*'),api('web_review_feed','select=*&order=created_at.desc&limit=30'),api('web_owner_ranking','select=*')]);renderReviews();renderOwnerRanking()}catch(e){console.warn(e);$('reviewSummary').textContent='오너평가 데이터를 불러오지 못했습니다.'}}
async function submitReview(e){e.preventDefault();const btn=$('reviewSubmit'),msg=$('reviewMessage'),gid=$('reviewVehicle').value;if(!gid)return;const values={};CRITERIA.forEach(([k])=>values[k]=Number(document.querySelector(`[name="${k}"]`).value));if(Object.values(values).some(v=>!v)){msg.textContent='10개 평가항목을 모두 선택해 주세요.';return}btn.disabled=true;msg.textContent='등록 중...';try{await rpc('submit_owner_review',{p_generation_id:gid,p_visitor_id:visitorId(),p_ride_comfort:values.ride_comfort,p_quietness:values.quietness,p_performance:values.performance,p_fuel_efficiency:values.fuel_efficiency,p_maintenance_cost:values.maintenance_cost,p_reliability:values.reliability,p_design:values.design,p_convenience:values.convenience,p_resale_value:values.resale_value,p_repurchase_intent:values.repurchase_intent,p_title:$('reviewTitle').value.trim()||null,p_body:$('reviewBody').value.trim()});msg.textContent='오너 평가와 리뷰가 등록되었습니다.';$('reviewForm').reset();await refreshOwnerData()}catch(err){console.error(err);msg.textContent=String(err).includes('already reviewed')?'이 브라우저에서는 해당 차량을 이미 평가했습니다.':'등록하지 못했습니다. 잠시 후 다시 시도해 주세요.'}finally{btn.disabled=false}}
async function load(){try{const [ranking,vehicles,compare,ratings,reviews,ownerRanking]=await Promise.all([api('web_value_ranking','select=*&order=retention_rate.desc'),api('web_vehicle_detail','select=*&order=brand.asc,model.asc,start_year.desc'),api('web_compare_base','select=*&order=brand.asc,model.asc'),api('web_rating_summary','select=*'),api('web_review_feed','select=*&order=created_at.desc&limit=30'),api('web_owner_ranking','select=*')]);if(ranking.length)DATA=ranking;VEHICLES=vehicles;COMPARE=compare;RATINGS=ratings;REVIEWS=reviews;OWNER_RANKING=ownerRanking}catch(e){console.warn('Supabase unavailable; fallback ranking remains active.',e)}renderHero();fillRankingFilters();renderRanking();fillVehicleSelectors();buildRatingFields();renderReviews();renderOwnerRanking()}
brand.onchange=renderRanking;category.onchange=renderRanking;$('closeDetail').onclick=()=>$('vehicleDetail').classList.add('hidden');$('scoreBrand').onchange=updateScoreVehicles;$('scoreBtn').onclick=showScore;$('compareBtn').onclick=()=>renderComparison([$('compare1').value,$('compare2').value,$('compare3').value].filter(Boolean));document.querySelectorAll('[data-pair]').forEach(b=>b.onclick=()=>quickCompare(b.dataset.pair));$('reviewForm').onsubmit=submitReview;load();