/* CarRanking homepage account/share controls */
(()=>{'use strict';const C=window.CARRANKING_CONFIG||{},BASE=String(C.supabaseUrl||'').replace(/\/+$/,''),KEY=C.supabasePublishableKey||'',TOKEN='carranking_access_token';const $=s=>document.querySelector(s);let mode='login';
async function auth(path,options={}){const r=await fetch(BASE+'/auth/v1/'+path,{...options,headers:{apikey:KEY,'Content-Type':'application/json'}}),t=await r.text();let x={};try{x=t?JSON.parse(t):{}}catch(_){}if(!r.ok)throw new Error(x.message||x.msg||t||'로그인 오류');return x}
function open(m){mode=m||'login';const signup=mode==='signup';$('#crAuthTitle').textContent=signup?'회원가입':'로그인';$('#crAuthGuide').textContent=signup?'이메일과 비밀번호로 가입합니다.':'가입한 이메일과 비밀번호를 입력하세요.';$('#crAuthSubmit').textContent=signup?'회원가입':'로그인';$('#crAuthPassword').autocomplete=signup?'new-password':'current-password';$('#crAuthModal').classList.remove('hidden');setTimeout(()=>$('#crAuthEmail')?.focus(),30)}
function close(){$('#crAuthModal')?.classList.add('hidden')}
async function submit(){const email=$('#crAuthEmail')?.value.trim(),password=$('#crAuthPassword')?.value||'',b=$('#crAuthSubmit'),signup=mode==='signup';if(!email)return alert('이메일을 입력해주세요.');if(password.length<8)return alert('비밀번호는 8자 이상 입력해주세요.');b.disabled=true;try{const d=await auth(signup?'signup':'token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});if(d.access_token)localStorage.setItem(TOKEN,d.access_token);alert(signup?(d.access_token?'회원가입과 로그인이 완료되었습니다.':'회원가입 확인 메일을 보냈습니다. 이메일 확인 후 로그인해주세요.'):'로그인되었습니다.');close()}catch(e){alert((signup?'회원가입':'로그인')+' 오류: '+e.message)}finally{b.disabled=false}}
async function resetPassword(){const email=$('#crAuthEmail')?.value.trim();if(!email)return alert('이메일을 먼저 입력해주세요.');try{await auth('recover?redirect_to='+encodeURIComponent('https://carranking.kr/'),{method:'POST',body:JSON.stringify({email})});alert('비밀번호 재설정 메일을 보냈습니다.')}catch(e){alert(e.message==='email rate limit exceeded'?'이메일 발송 한도를 초과했습니다. 잠시 후 다시 시도해주세요.':'재설정 메일 오류: '+e.message)}}
function share(){const text=encodeURIComponent('CarRanking - 자동차 순위·가치보존율·오너평점\n'+location.href),route=encodeURIComponent(location.hostname||'carranking.kr');if(/Android|iPhone|iPad/i.test(navigator.userAgent)){location.href='bandapp://create/post?text='+text+'&route='+route;setTimeout(()=>window.open('https://band.us/plugin/share?body='+text+'&route='+route,'share_band','width=410,height=540,resizable=yes'),700)}else window.open('https://band.us/plugin/share?body='+text+'&route='+route,'share_band','width=410,height=540,resizable=yes')}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.cr-auth-open').forEach(b=>b.onclick=()=>open(b.dataset.mode));document.querySelectorAll('[data-cr-close]').forEach(b=>b.onclick=close);$('#crAuthSubmit').onclick=submit;$('#crAuthReset').onclick=resetPassword;['crAuthEmail','crAuthPassword'].forEach(id=>$('#'+id).onkeydown=e=>{if(e.key==='Enter')submit()});$('#crBandShare').onclick=share;document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})});
})();